services:
  audio_dashboard:
    image: node:14
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
    command: node server.js
    ports:
      - "8000:8000"

  audio_stream:
    build: ./audio_stream
    working_dir: /usr/src/audio_stream
    volumes:
      - ./audio_stream:/usr/src/audio_stream