services:
  app:
    build: ./app
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "443:443"
    environment:
      - NODE_ENV=production
